-- 코드를 작성해주세요
# SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
# FROM HR_DEPARTMENT D, HR_EMPLOYEES E, HR_GRADE G
# WHERE D.DEPT_ID = E.DEPT_ID
#     AND E.EMP_NO = G.EMP_NO
# GROUP BY E.EMP_NO
# ORDER BY G.SCORE DESC
# LIMIT 1;

SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SCORE DESC
LIMIT 1;

# SELECT SUM(B.SCORE) SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
# FROM HR_EMPLOYEES A JOIN HR_GRADE B
# ON A.EMP_NO = B.EMP_NO
# GROUP BY B.EMP_NO
# ORDER BY 1 DESC
# LIMIT 1;